### ISSUE TITLE
Support future responses

### ISSUE THREAD

**Issue by codeliner** [prooph/psb-zeromq-producer#5]
zeromq supports [request / response scenarios](http://zguide.zeromq.org/page:all#Ask-and-Ye-Shall-Receive). We should add that feature and handle a deferred if it is given.

**Comment by codeliner** [comment]
@bweston92 Can you take over the task?

**Comment by bweston92** [comment]
@codeliner I will do, I did mention this in #1 as a future goal. I will read more into it on ZMQ side and get it going.

**Comment by codeliner** [comment]
That sounds great. Next week I will have some more time to play with zeromq. What I saw so fare is really cool. zeromq seems to be very lightweight way to add async messaging to an application. I'm glad to have zeromq support on board. Thanks again for your great work :+1:

**Comment by codeliner** [comment]
Done with #8
